///////////////////////////////////////////////////////////
//  DuplirajPlaner.cs
//  Implementation of the Class DuplirajPlaner
//  Generated by Enterprise Architect
//  Created on:      25-Aug-2021 3:06:02 PM
//  Original author: Filip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common.Models;
using Client.Models;



namespace Client.Command {
	public class DuplirajPlaner : PlanerCommand {

		public DuplirajPlaner(Planner planer, PlanerModel planerModel){
            PrethodniPlaner = planer;
            PlanerModel = planerModel;
		}

		~DuplirajPlaner(){

		}

		public override bool Redo(){
            if (PlanerModel.connection.planerServiceProxy.Exists(PrethodniPlaner.PlannerId))
            {
                var noviPlaner = PrethodniPlaner.Clone() as Planner;
                int planerId = PlanerModel.connection.planerServiceProxy.SavePlaner(noviPlaner);
                noviPlaner.PlannerId = planerId;
                PlanerModel.Planers.Add(noviPlaner);
                PrethodniPlaner = noviPlaner;
                PlanerModel.Planers.Refresh();
                log.Info($"Uspesno je izvrsena komanda dupliranja Planera [ planerId = {planerId} ].");
                return true;
            }
            log.Error($"Doslo je do greske prilikom izvrsavanja komande dupliranja Planera [ planerId = {PrethodniPlaner.PlannerId} ].");
            return false;
        }

		public override bool Undo(){
            var ret = PlanerModel.connection.planerServiceProxy.RemovePlaner(PrethodniPlaner);
            if (ret)
            {
                PlanerModel.Planers.Remove(PrethodniPlaner);
                PlanerModel.Planers.Refresh();
                log.Info($"Uspesno ponistavanje komande dupliranja Planera [ planerId = {PrethodniPlaner.PlannerId} ].");
            }
            else
            {
                log.Error($"Doslo je do greske prilikom pokusaja ponistavanja komande dupliranja Planera [ planerId = {PrethodniPlaner.PlannerId} ].");
            }
            return ret;
        }

	}//end DuplirajPlaner

}//end namespace EventPlanner