///////////////////////////////////////////////////////////
//  DuplirajPlaner.cs
//  Implementation of the Class DuplirajPlaner
//  Generated by Enterprise Architect
//  Created on:      25-Aug-2021 3:06:02 PM
//  Original author: Filip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common.Models;
using Client.Models;



namespace Client.Command {
	public class DuplirajPlaner : PlanerCommand {

		public DuplirajPlaner(Planner planer, PlanerModel planerModel){
            PrethodniPlaner = planer;
            PlanerModel = planerModel;
		}

		~DuplirajPlaner(){

		}

		public override bool Redo(){
            var noviPlaner = PrethodniPlaner.Clone() as Planner;
            int planerId = connection.planerServiceProxy.SavePlaner(noviPlaner);
            noviPlaner.PlannerId = planerId;
            PlanerModel.Planers.Add(noviPlaner);
            PrethodniPlaner = noviPlaner;
            PlanerModel.Planers.Refresh();
            return true;
        }

		public override bool Undo(){
            var ret = connection.planerServiceProxy.RemovePlaner(PrethodniPlaner);
            if (ret)
            {
                PlanerModel.Planers.Remove(PrethodniPlaner);
                PlanerModel.Planers.Refresh();
            }
            return ret;
        }

	}//end DuplirajPlaner

}//end namespace EventPlanner