///////////////////////////////////////////////////////////
//  ObrisiPlaner.cs
//  Implementation of the Class ObrisiPlaner
//  Generated by Enterprise Architect
//  Created on:      25-Aug-2021 3:06:01 PM
//  Original author: Filip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common.Models;
using Client.Models;



namespace Client.Command {
	public class ObrisiPlaner : PlanerCommand {

		public ObrisiPlaner(Planner planer, PlanerModel planerModel){

            PrethodniPlaner = planer;
            PlanerModel = planerModel;
		}

		~ObrisiPlaner(){

		}

		public override bool Redo(){
            foreach (var planer in PlanerModel.Planers)
            {
                if (planer.PlannerId == PrethodniPlaner.PlannerId)
                {
                    connection.planerServiceProxy.RemovePlaner(planer);
                    PlanerModel.Planers.Remove(planer);
                    PlanerModel.Planers.Refresh();
                    return true;
                }
            }
            return false;
        }

		public override bool Undo(){
            int planerId = connection.planerServiceProxy.SavePlaner(PrethodniPlaner);
            PrethodniPlaner.PlannerId = planerId;
            PlanerModel.Planers.Add(PrethodniPlaner);
            PlanerModel.Planers.Refresh();
            return true;
        }

    }//end ObrisiPlaner

}//end namespace EventPlanner