///////////////////////////////////////////////////////////
//  ObrisiPlaner.cs
//  Implementation of the Class ObrisiPlaner
//  Generated by Enterprise Architect
//  Created on:      25-Aug-2021 3:06:01 PM
//  Original author: Filip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common.Models;
using Client.Models;



namespace Client.Command {
	public class ObrisiPlaner : PlanerCommand {

		public ObrisiPlaner(Planner planer, PlanerModel planerModel){

            PrethodniPlaner = planer;
            PlanerModel = planerModel;
		}

		~ObrisiPlaner(){

		}

		public override bool Redo(){
            foreach (var planer in PlanerModel.Planers)
            {
                if (planer.PlannerId == PrethodniPlaner.PlannerId)
                {
                    var ret = PlanerModel.connection.planerServiceProxy.RemovePlaner(planer);
                    if (ret)
                    {
                        PlanerModel.Planers.Remove(planer);
                        PlanerModel.Planers.Refresh();
                        log.Info($"Uspensno izvrsena komanda brisanja Planera [ planerId = {planer.PlannerId} ].");
                        Client.ViewModels.LogViewModel.AddLog(DateTime.Now, "INFO", $"Uspensno izvrsena komanda brisanja Planera [ planerId = {planer.PlannerId} ].");

                    }
                    return ret;
                }
            }

            log.Error($"Doslo je do greske prilikom pokusaja izvrsavanje komande brsianja Planera.");
            Client.ViewModels.LogViewModel.AddLog(DateTime.Now, "ERROR", $"Doslo je do greske prilikom pokusaja izvrsavanje komande brsianja Planera.");

            return false;
        }

		public override bool Undo(){
            int planerId = PlanerModel.connection.planerServiceProxy.SavePlaner(PrethodniPlaner);
            PrethodniPlaner.PlannerId = planerId;
            PlanerModel.Planers.Add(PrethodniPlaner);
            PlanerModel.Planers.Refresh();

            log.Info($"Usepeno je izvrseno ponistavanja komande brisanja Planera [ planerId = {planerId} ].");
            Client.ViewModels.LogViewModel.AddLog(DateTime.Now, "INFO", $"Usepeno je izvrseno ponistavanja komande brisanja Planera [ planerId = {planerId} ].");

            return true;
        }

    }//end ObrisiPlaner

}//end namespace EventPlanner